version: '3.6'

services:

  # Route HTTP requests to specific containers based on the HTTP_HOST header.
  nginx-proxy:
    image: jwilder/nginx-proxy:1.0.4
    depends_on:
      - mkcert
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - cert_data:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./local/docker/nginx-proxy/conf.d/custom.conf:/etc/nginx/conf.d/custom.conf

  # Create a local DNS server that maps all *.local.wpengine.test to this environment when not connected to the internet.
  # Append `--log-queries --log-facility=-` to the command to enable verbose logging to stderr of all lookups.
  dnsmasq:
    image: andyshinn/dnsmasq:2.83
    ports:
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    command: --address=/${DEV_URL:-local.wpengine.test}/${DOCKER_HOST_IP:-"127.0.0.1"} --server=1.1.1.1

  # Generate SSL certs for the local development environment.
  mkcert:
    build: ./local/docker/mkcert
    volumes:
      - cert_data:/root/.local/share/mkcert
    command: mkcert -cert-file "${DEV_URL:-local.wpengine.test}.crt" -key-file "${DEV_URL:-local.wpengine.test}.key" "${DEV_URL:-local.wpengine.test}" "*.${DEV_URL:-local.wpengine.test}"

  db:
    image: mariadb:10.3
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.0
    depends_on:
      - db
    environment:
      VIRTUAL_HOST: phpmyadmin.${DEV_URL:-local.wpengine.test}
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root

  # Capture all emails sent by WordPress.
  mailhog:
    image: mailhog/mailhog:v1.0.1
    environment:
      VIRTUAL_HOST: mail.${DEV_URL:-local.wpengine.test}
      VIRTUAL_PORT: 8025

  # For WP object caching.
  memcached:
    image: memcached:1.6

  # Review Xdebug profiling data.
  webgrind:
    image: jokkedk/webgrind:latest
    volumes:
      - webgrind_data:/tmp
    environment:
      VIRTUAL_HOST: webgrind.${DEV_HOSTNAME:-local.wpengine.test}

  wordpress:
    depends_on:
      - db
    build: ./local/docker/wordpress
    restart: always
    volumes:
      - ./local/public:/var/www/html
      - .:/var/www/html/wp-content
      - webgrind_data:/tmp
    command: bash -c "wp core multisite-install --url=${DEV_URL:-local.wpengine.test} --allow-root && docker-entrypoint.sh apache2-foreground"
    environment:
      VIRTUAL_HOST: ${DEV_URL:-local.wpengine.test}, *.${DEV_URL:-local.wpengine.test}
      SMTPSERVER: mailhog
      EMAIL: local@${DEV_URL:-local.wpengine.test}
      XDEBUG_MODE: debug,coverage # Append `profile` to enable profiling or leave empty to disable all.
      XDEBUG_CONFIG: client_host=host.docker.internal discover_client_host=0 # Required for MacOS only.
      WP_PHPUNIT__TESTS_CONFIG: local/public/wp-tests-config.php

volumes:
  db_data:
  cert_data:
  webgrind_data:
