name: Test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install NPM dependencies
        run: npm ci

      - name: Install Composer dependencies
        run: composer install

      - name: Build
        run: npm run build

      - name: Unit-tests
        run: npm run test
